version: '3.8'

services:
  redis-score:
    image: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
      # - 6379:6379
    volumes:
      - .db:/data
    restart: always
    entrypoint: redis-server --appendonly yes
  score-api:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      DATABASE_URL: redis://redis-score:6379

networks:
  default:
    external: true
    name: snapshot-network
