version: '3.8'

services:
  score-api:
    build: .
    container_name: score-api
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      RATE_LIMIT_DATABASE_URL: redis://redis:6379
      DATABASE_URL: redis://redis:6379  

networks:
  default:
    name: snapshot-network